### ISSUE TITLE
gunzip *cd .. typo error

### ISSUE THREAD

**Issue by yvanlebras** [bwawrik/MBIO5810#16]
Hi @bwawrik ,

It seems that there is maybe a typo error at the beginning of the [basic Qiime tuto](https://github.com/bwawrik/MBIO5810/blob/master/06_BASIC_QIIME_TUTORIAL.md) when you mention : 

```
cd Silva_111_post/rep_set_aligned
gunzip *cd ..
cd rep_set
gunzip *
```

Thank you for this tutorial!

Cheers,

Yva

**Comment by bwawrik** [comment]
fixed.

I'm glad it helped !
